config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	validates_presence_of :caption
  has_one_attached :content, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  # has_many :followers, foreign_key: :follower_id , class_name: "Companion"
  # has_many :followed, foreign_key: :followed_id, class_name: "Companion"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, only: %i[ show edit update destroy ]


  def create
    @post = current_user.posts.new(post_params)
    @post.save
    @posts = Post.all
  end

  def update
    @post.update(post_params)
    @posts = Post.all
  end

  def destroy
    @post.destroy
    @posts = Post.all
  end

  private

    def set_post
      @post = Post.find_by(id: params[:id])
    end

    def post_params
      params.require(:post).permit(:caption, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/home/_posts.html.erb
<div style="display: none;" class="m-5" id="new-post-form" onclick="showNewForm()" >
  <%= form_with model: Post.new, url: posts_path, id: 'new_form' do |form| %>
    <div class="row">
        <div class="col-md-2 pl-1">
          <%= form.label :caption %>
          <%= form.text_field :caption, class: 'form-control', require: true %>
        </div>
        <div class="col-md-2 p-0">
          <%= form.label :content %>
          <%= form.file_field :content, class: 'form-control' %>
        </div>
        <div class="col-md-2 py-4" >
          <%= form.submit 'Post', class: 'btn-sm btn btn-primary' %>
        </div>
    </div>
  <% end %>
</div>

<% @posts.each do |post| %>
  <div class="row m-5" id="post_<%= post.id %>">
      <div class="col-md-2">
        <% if post.content.attached? %>
          <% if post.content.image? %>
        	  <%= image_tag post.content, height:'150', width: '150' rescue nil %>
          <% else %>
            <%= video_tag post.content, height:'150', width: '150', controls: true rescue nil %>
          <% end %>
        <% end %>
      </div>
    <div class="col-md-2">
      <br>
      <b class="margin-left">caption: </b><%= post.caption %>
      <br>
    </div>
    <div class="col-md-2 py-4">
      <%= link_to 'Edit', 'javascript:;',  onClick: "showForm(#{post.id})" %>
    </div>
    <div class="col-md-2 py-4">
      <%= link_to 'Destroy', 'javascript:;',  onClick: "destroyPost(#{post.id})" %>
    </div>
  </div>
  <div class="row m-5" style="display: none" id="post_form_<%= post.id %>">
    <%= form_with model: post, url: post_path(post), data: {post_id: post.id}, method: :put, id: "update_form" do |form| %>
      <div class="row">
          <div class="col-md-2 pl-1">
            <%= form.label :caption %>
            <%= form.text_field :caption, class: 'form-control', require: true %>
          </div>
          <div class="col-md-2 p-0">
            <%= form.label :content %>
            <%= form.file_field :content, class: 'form-control' %>
          </div>
          <div class="col-md-2 py-4" >
            <%= form.submit 'Update', class: 'btn-sm btn btn-primary' %>
          </div>
      </div>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
  function showForm(postId) {
    if (postId) {
      $(`#post_${postId}`).hide();
      $(`#post_form_${postId}`).show();
    }
  }
  function showNewForm() {
    $('#new-post-form').show()

  }
  function destroyPost(postId){
    $.ajax({
            url: '/posts/' + postId,
            method: 'DELETE',
            data: { 
              authenticity_token: $('meta[name="csrf-token"]').attr('content')
            },
            dataType: "script",
          });
  }

  $('#update_form').on('submit', function(e) {
    e.preventDefault();
    let formData = new FormData(this);
    let postId = $(this).data('post-id')
    $.ajax({
      url: '/posts/' + postId,
      method: 'PUT',
      data: formData,
      contentType: false,
      processData: false,
      dataType: "script"
    })
  })

  $('#new_form').on('submit', function(e) {
    e.preventDefault();
    let formData = new FormData(this);
    $.ajax({
      url: '/posts',
      method: 'POST',
      data: formData,
      contentType: false,
      processData: false,
      dataType: "script"
    })
  })

  </script>

app/views/home/index.html.erb
<div id="posts">
	<%= render 'posts' %>
</div>

app/views/home/index.js.erb
$('#posts').html("<%= j ( render 'posts' )%>")

app/views/layouts/_headers.html.erb
<style type="text/css">
	ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
}
ul#navbar{
	padding: 10px;
  background-color: #dddddd;
}
a {
  padding: 8px;
}
li button {
  background: none;
  border: none;
  text-decoration: underline;
  color: blue;
}

</style>
<% if user_signed_in? %>
  <ul id="navbar">
    <li><%= link_to 'New Post', 'javascript:;', onclick: 'showNewForm()' %></li>
    <li><%= button_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwickApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: '/layouts/headers' %>
    <%= yield %>
  </body>
</html>

app/views/posts/create.js.erb
$('#posts').html("<%= j( render '/home/posts') %>")

app/views/posts/destroy.js.erb
$('#posts').html("<%= j ( render 'home/posts' )%>")

app/views/posts/update.js.erb
$('#posts').html("<%= j ( render 'home/posts' )%>")

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>